### ISSUE TITLE
How can i use locally ?

### ISSUE THREAD

**Issue by pauld8758757** [krauchenco/nagioscfg2json#4]
Hi. I tried to use directly in a browser calling it from an html file but didn't manage it. I guess i didn't get how to use it. can you help?

**Comment by krauchenco** [comment]
You need use NodeJS. When you install NodeJS, NPM will be available to install and use the package.

You install a package using this command
$ npm install nagioscfg2json

And you need to write a NodeJS program like this:

var nagioscfg2json = require('nagioscfg2json');
nagioscfg2json.fromFile('localhost_nagios2.cfg', function (err, json){
    if (err) {
        console.log(err);
        return;
    }
    console.log(JSON.stringify(json, null, 4));
});

In this snippet, a file in path of script named localhost_nagios2.cfg will be parsed to javascript and shown in output.

You cannot use a browser to run this script because the package not be found without a npm and NodeJS environment, ok?

I just posted the 0.0.2 version, with some corrections.
